
version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - $PWD/nginx/public:/var/www/html/
      - $PWD/nginx/conf.d/ssi.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  header:
    container_name: header
    build:
      context: ./header
    volumes:
      - $PWD/header:/usr/src/app
    ports:
      - "5001:5001"
    environment:
      PORT: 5001

  body:
    container_name: body
    build:
      context: ./body
    volumes:
      - $PWD/body:/usr/src/app
    ports:
      - "5002:5002"
    environment:
      PORT: 5002

  footer:
    container_name: footer
    build:
      context: ./footer
    volumes:
      - $PWD/footer:/usr/src/app
    ports:
      - "5003:5003"
    environment:
      PORT: 5003  
